### PR TITLE
fix: update components to use arrow function syntax

### PR DESCRIPTION
**Pull request by chrismanciero**
PR for issue #171

### CODE REVIEW

**Comment by chrismanciero** [comment]
thanks @greg-a-smith, i missed that file. For the indent spacing i setup my VS Code to Prettier extension to look at the eslint file for formatting on save. Here is the rule in the file **#indent: [2, 4, {"SwitchCase": 1}]** which i think is commented out.

**Comment by greg-a-smith** [comment]
@chrismanciero Yes, that's the lint rule.  It's still commented out because there are a number of places that fail when enabled.  Our plan was to circle back and make the fixes necessary to satisfy the rules as we enable them.  It will likely be a number of PRs until they are all enabled.  I'm fine leaving the changes in this PR and then everything will be addressed when the work to enable that rule is done.

**Comment by mobot11** [comment]
To piggyback off of what @greg-a-smith  said, I opened https://github.com/SAP/fundamental-react/issues/174 to create a .editorconfig so we can don't have to think about our editor settings when making contributions to the repo.

**Comment by bcullman** [comment]
consider adding a backing eslint rules for this:

https://eslint.org/docs/rules/arrow-body-style

**Comment by chrismanciero** [comment]
Sure no problem, the merge is still blocked until @greg-a-smith resolves his request, which i am assuming he is waiting until the automated version is resolved 😄

**Comment by greg-a-smith** [comment]
@chrismanciero Do you want to take a shot at adding a https://eslint.org/docs/rules/arrow-body-style lint rule while this PR is on hold?

**Comment by chrismanciero** [comment]
@greg-a-smith sure i can take a look today, is there a specific option we want set by default for this lint rule?

**Comment by greg-a-smith** [comment]
@chrismanciero Actually, looking at that rule, I think I misunderstood it.  I initially took it as a rule that would enforce the use of arrow functions for component methods, but this rule is simply for the syntax of the function body.  Although we could maybe look into rules like this in the future, I don't think this rule relates to this PR.  We have not used any of these rules in our SAP Concur repo so we don't have any experience with them yet.

**Pull request merged**
