### PR TITLE
Fix unique `key` prop error in Menu.Item and SearchInput

### LINKED ISSUE #512: Shellbar causes multiple React keys warnings
### Description
When using the Shellbar component, multiple errors come up in the console.

Upon mount:
```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div
    in div
    in div (created by SearchInput)
    in SearchInput
    in div
    in div
    in div
    in div
    in Shellbar
...
```
Upon click on the user menu:
```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in Menu.Item
    in ul (created by Menu.List)
    in Menu.List
    in nav (created by Menu)
    in Menu
    in div (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper
    in span (created by Foco)
    in Foco
    in Manager
    in Popper
    in Popover
    in div
    in div
    in div
    in div
    in div
    in Shellbar 
...
```

The mounted shellbar has a search input as well as a user menu. 

### Versions
**fundamental-react:** 0.5.0
**fiori-fundamentals:** 1.5.1
**react**: 16.8.1

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by parostatkiem**
### Changes
- add and document `uniqueKey` prop in Menu.Item (fixes error when used)
- add unique `key` prop to SearchInput's internal Button element (fixes error)
- Add key to input element inside Toggle component (fixes error)

fixes #512

### CODE REVIEW

**Comment by bcullman** [comment]
Thanks for the PR couple of thoughts

Should probably should set default prop with https://github.com/SAP/fundamental-react/blob/master/src/utils/shortId.js

Need to add a backing unit test.

**Comment by parostatkiem** [comment]
@bcullman Thanks for looking at it.
`shortId` generates a new ID with every execution of `shortId.generate()`, am I right?
If yes, every outter component render would cause them to regenerate. This would have negative impact on React's performance - the whole idea of list items' keys would be gone (they have to be static and different for each item). 

I'll take care of unit tests.

**Comment by sjanota** [comment]
I've been playing a little with this PR and it looks like components are working perfectly well when I copy the JSX code to my project. However, when I use a compiled version from npm it throws the react error.

**Comment by parostatkiem** [comment]
@sjanota This may be connected with the fact that none of these errors is thrown on the Documentation Website, even in dev mode but they are thrown when the same components are used in another app.

**Comment by sjanota** [comment]
I've been playing with it a while, but haven't found anything concrete. I'm pretty sure it's in the way the library is compiled, though. I left a comment [here](https://github.com/SAP/fundamental-react/issues/512#issuecomment-531192816).

**Comment by parostatkiem** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/741

**Pull request closed without merging**
