### PR TITLE
chore: Increased win compatibility for building

### LINKED ISSUE #1246: Running `npm run build` under Windows fails due to usage of `rm` in the build script - please use cross-platform alternative like rimraf
### Description

I cloned the repository under Windows and run `npm i` (works) and then `npm run build`. Building fails with the error "the command rm cannot be found". 

Other open source projects I'm aware of use the npm package rimraf for implementing deletion steps in a cross-platform manner.

### Versions
**fundamental-react:** Current master branch at the time of filing this issue

### PR DESCRIPTION
**Pull request by huberv**
### Description

fixes #1246

I added rimraf as dev dependency. I use npm@7 and got a "lockfileVersion: 2" in the adjusted package-lock.json in addition to the adjustments for the rimraf package - that's why I did not commit the changes on the package-lock.json on purpose.

When running the pre-commit linting, I found I had to change the *nix "printf" to an "echo" and tell stylelint to auto-determine line endings as well instead of checking for *nix line endings.

### CODE REVIEW

**Review by prsdthkr — APPROVED** [review]
LGTM. Build and pre-commit scripts working on Windows and macOS.

**Review by Mike-Diaz — APPROVED** [review]

**Comment by jbadan** [comment]
@prsdthkr @Mike-Diaz We might need to remake this pr so we can commit the package-lock with it.

**Comment by prsdthkr** [comment]
@jbadan I `npm installed` and saw no related package-lock changes 🤔

**Comment by jbadan** [comment]
closing in favor of https://github.com/SAP/fundamental-react/pull/1261

**Comment by jbadan** [comment]
@prsdthkr Sorry, I just saw your comment. I saw you added rimraf in another pr, but I wanted to move it to dev deps instead.

**Pull request closed without merging**
