### PR TITLE
Pagination control

### PR DESCRIPTION
**Pull request by chrismanciero**
Initial commit of the Pagination control. This control will allow users to display a collection of links (page numbers) as well as a Previous and Next button. The total number of pages is determined by the total number of items.

This control is for the issue: https://github.com/SAP/fundamental-react/issues/11

### CODE REVIEW

**Comment by droshev** [comment]
@chrismanciero first of all, thank for your contribution. It is very much appreciated 👍 
Regarding the implementation - I guess it is an initial implementation of the component as at the moment you show all the pages as link and no ellipsis when there are many pages per fundamental.
Are you willing to implement that part too?

**Comment by chrismanciero** [comment]
@droshev - You're welcome and Yes this in an initial implementation. I decided to leave out the ellipsis in the control until I have a better understanding of how it should behave.

For example: https://sap.github.io/fundamental/components/pagination.html#in-between-more-than-three-pages 

- I noticed that the ellipsis it not clickable, should it be?

- What should happen when a user clicks on the ellipsis? Should the ellipsis behave like the Contextual Menu control (https://sap.github.io/fundamental/components/contextual-menu.html#with-icon) where when clicked it displays all the pages between

- When navigating using the Previous or Next button, if you go from a displayed number to the ellipsis, what happens?

**Comment by droshev** [comment]
@chrismanciero let me come to you later. I have brought your questions  to the team. We can add you to the contributors so you won't need to fork - what do you think?

**Comment by droshev** [comment]
@chrismanciero I discussed with @jeannewalters and @LeoT7508 your points. Here are the answers:

> No it should not. It should be a gray color instead of blue as it's not clickable.

> When there is an ellipsis, the selected page should always be in the 4th position

 The issue has been raised to @saadmhybris so they can improve it in fundamental-ui (the design and implementation)

**Pull request merged**
