### PR TITLE
fix: Updating Dependencies

### LINKED ISSUE #111: Cleanup dependencies
Looking through the dependencies, it appears some of the dependencies can be moved to devDependencies and some can be moved to peerDependencies.  Organizing dependencies properly can dramatically reduce the size of the package.

CORUI-5995

### PR DESCRIPTION
**Pull request by jeffredodd**
The goal of this PR is to migrate the documentation/build-time dependencies (Webpack, babel, PostCSS, and their various plugins etc) to `devDependencies` while the `dependencies` should only directly relate to the required libraries for consumers of the widgets. 

Also in this PR I have introduced `react` and `react-dom` as peerDependencies. This will reduce our dependencies while giving our consumers some flexibility. 

This resolves #111 and is a pre-requisite for #105 and #115.

### CODE REVIEW

**Comment by jeffredodd** [comment]
@mobot11 also in this files defence, I think the create-react-app ejection is responsible for the majority of these dependencies being in the `dependencies` section.

**Comment by jeffredodd** [comment]
@droshev I think for now a large list of devDeps is ok since our future consumers won't be required to install the devDeps. In a future PR, #115, our deps will get even smaller as we won't need react router for the documentation except for local development and the demo site publishing. 😄

**Comment by jeffredodd** [comment]
❓ I think we are pretty close to merging this, anyone have thoughts around merging? ❓

**Comment by droshev** [comment]
@jeffredodd i am fine

**Pull request merged**
