### PR TITLE
fix: manually updated rc version

### PR DESCRIPTION
**Pull request by hertweckhr1**
### Description
I merged my previous PRs too quickly from splitting tests.  I manually updated the rc version because of this.

### CODE REVIEW

**Comment by greg-a-smith** [comment]
This seems like a bad idea.  Why does this need to be updated?

**Comment by hertweckhr1** [comment]
@greg-a-smith because I had merged too fast not fully completing the process in travis and the rc version was not matching up from the release page with package.json, Jenna suggested updating it manually.  @jbadan might have a better explanation.

**Comment by greg-a-smith** [comment]
@hertweckhr1 Looking at npmjs.com, rc 9 never actually made it to getting published (see screenshot).  I think the better approach might be removing the rc 9 tag from the repo.

Screen Shot 2019-05-08 at 11 55 37 AM

**Comment by hertweckhr1** [comment]
At @greg-a-smith's insight, deleted release tag for 0.5.2 rc 9 so no need to change manually.

**Pull request closed without merging**
