### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by chrismanciero**
This branch should contain the Git History of renaming the .js file to .tsx

### CODE REVIEW

**Comment by greg-a-smith** [comment]
As one of the developers with SAP Concur, I know we are new to this repository.  We are excited to make some contributions and help move these components (and the repository) forward.

My goal with this PR review is not to offer opinions on whether a move to TypeScript is the right choice or not, but rather to point out that our team has assembled a number of stories/tasks to "Production-ize" this repository to be consumed by the SAP Concur react library.  See [Production-ize fundamental-react project](https://github.com/SAP/fundamental-react/projects/2).

Our team is prepared to make these changes (in fact, we have already started work on a few), but feel a move to TypeScript at this time would hinder that progress.  Is this something that could be shelved and discussed again once the repository has been Production-ized?

As an aside, there are currently some `jsx-a11y` lint rules that are not supported by TypeScript (either not supported or are currently failing).  In order for SAP Concur to use this repository, components must be accessible and these rules are very helpful in identifying potential issues up front.

**Comment by droshev** [comment]
@greg-a-smith we didn't make our mind yet. Any feedback coming from experienced react developers are very much appreciated.

**Comment by chrismanciero** [comment]
Hi @greg-a-smith, thanks for the insight. Just a little background of this PR. There was a topic brought up about adding a type checking system to the library (Flow or TypeScript). In my downtime I took a shot at learning TypeScript while converting some of the components to use TypeScript, some component turned into a majority of them 😄 

I am all for waiting on the switch to TypeScript or Flow or neither once this library is productized. I agree with @droshev that any feedback from experienced react developers would be great.

**Comment by chrismanciero** [comment]
Since the topic of if/when the transition to TypeScript is still ongoing and this branch was more created to show the changes needed to switch to TypeScript I have decided to close it to prevent any unwanted merges to the develop branch

**Comment by greg-a-smith** [comment]
@chrismanciero I completely understand how changes like that go. :)

@droshev, @chrismanciero Thanks for the notes.  Our team has maintained a very similar component-type library using React for the past few years and have multiple React applications running in Production that consume our library.  We see all the excellent work already done in this repository that can quickly accelerate our adoption of Fiori.  We certainly don't claim to know all the answers or best practices, but are more than willing to contribute our experience and learnings.

**Pull request closed without merging**
