### PR TITLE
feat: upgrade fundamental-styles to 13.0-rc.5

### PR DESCRIPTION
**Pull request by jacobdevera**
### Description
- upgrade fd-styles to 13.0-rc.5
    - remove `LocalizationEditor`
    - add `full` prop to `Column`
    - few changes to gridManager to better handle multi colSpan rows

### CODE REVIEW

**Comment by jbadan** [comment]
@jacobdevera Are you using node 12 and still getting these netlify deploy errors?

**Review by meganaconley — APPROVED** [review]
Tested locally, all looks good

**Comment by skvale** [comment]
When merging let's make sure the commit message starts with
```
BREAKING CHANGE: ...
```
otherwise the commit
```
feat: upgrade fundamental-styles to 13.0-rc.5 (#1243)

* feat: rc.16, full columns

* chore: 13.0-rc.0, remove LocalizationEditor

* chore: rc.5

* fix: colSpan handling

* fix: cell validity

* fix: tests

* fix: first focused cell, get next cell defined
```
just turns into this in the CHANGELOG
```

Features
upgrade fundamental-styles to 13.0-rc.5 (#1243) (f39eecc)
```

**Comment by jacobdevera** [comment]
Ah, I forgot to add it to the commit message. Should I make a dummy PR so that it makes it in the changelog?

**Pull request merged**
