### PR TITLE
chore: add babel plugin to remove prop descriptions from prod build

### PR DESCRIPTION
**Pull request by mobot11**
### Description
Leverages code from https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/tree/master/src to remove prop descriptions from production build.

fixes https://github.com/SAP/fundamental-react/issues/376

### CODE REVIEW

**Comment by greg-a-smith** [comment]
I like the premise of this.  I'm just a little unsure about the volume of code we are ingesting to make it happen (and code we basically didn't write).  So, I guess I'm neither in favor of it nor against it.  I'd be interested in hearing thoughts from others.

**Comment by jbadan** [comment]
Same as @greg-a-smith, just dropping a note that we need to coordinate as this pr will not play nicely with https://github.com/SAP/fundamental-react/pull/378

**Comment by mobot11** [comment]
We get about a 5KB size decrease by using this. While not a whole lot, it could end up being significant as the library grows in size.

**Comment by mobot11** [comment]
Closing

**Pull request closed without merging**
