### PR TITLE
fix: fix isCssModulesEnabled check when styles is undefined and improve setup in README

### PR DESCRIPTION
**Pull request by skvale**
### Description

fix isCssModulesEnabled check when styles is undefined and improve setup in README

fixes #issueid

### CODE REVIEW

**Review by prsdthkr — APPROVED** [review]

**Review by jbadan — APPROVED** [review]

**Comment by skvale** [comment]
why are my builds hanging forever

**Comment by prsdthkr** [comment]
Yep, this seems to be happening a lot recently. I've restarted the build.

**Comment by prsdthkr** [comment]
Eeeeshhh 🙄

**Comment by prsdthkr** [comment]
I think moving to travis.com will reduce build times.
image

**Comment by jbadan** [comment]
@prsdthkr For a little bit, but once everyone moves over after .org is no longer supported it will be even worse.

**Comment by prsdthkr** [comment]
@droshev pointed this out

🤯 
image

**Comment by jbadan** [comment]
@prsdthkr I've opened multiple issues in their repo asking them to work on their build times and they don't want to haha

**Pull request merged**
